In [1]:
a = 23
print(a)

23

In [2]:
b = 12
print(a+b)

35

In [4]:
ma_valeur = 70
une_autre = 37
total = ma_valeur + une_autre
print(f"le total est de {total} €")

le total est de 107 €

In [1]:
valeur1, valeur2 = input("entrz la valeur1"), input("entrez la valeur2")
total = int(valeur1) + int(valeur2)
print(f"le total est de {total} €")

le total est de 90 €

In [2]:
["pair" if i % 2 == 0 else "impair" for i in range(20)]

['pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair',
 'pair',
 'impair']

In [1]:
!pwd

/Users/thierrylegros/00-JEDHA/Fullstack-AI/PrepWork

In [7]:
print([i*i for i in range(1,65)])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096]

In [ ]:
import pandas as pd

df_data = pd.read_csv("/Users/thierrylegros/00-JEDHA/Fullstack-AI/PrepWork" + "/netflix_content_intelligence_combined.csv")

In [9]:
df_data.head(10)

,content_id,title,type,release_year,release_decade,release_year_group,content_age,date_added,rating,duration,...,primary_country,country_count,is_original,is_recent_release,has_rating,has_cast,has_director,data_completeness_score,match_method,match_confidence
0,nf_2879cda65363,3%,TV Show,2020,2020,2020-2022,6,"August 14, 2020",TV-MA,4 Seasons,...,Brazil,1,False,False,True,True,False,0.857,fuzzy_title_year,0.89
1,nf_73818ff7bd91,7:19,Movie,2016,2010,2016-2019,10,"December 23, 2016",TV-MA,93 min,...,Mexico,1,False,False,True,True,True,1.000,exact_title_year,0.90
2,nf_821496e58bca,23:59,Movie,2011,2010,2010-2015,15,"December 20, 2018",R,78 min,...,Singapore,1,False,False,True,True,True,1.000,exact_title_year,0.90
3,nf_be2013d8c4ac,9,Movie,2009,2000,2000s,17,"November 16, 2017",PG-13,80 min,...,United States,1,False,False,True,True,True,1.000,exact_title_year,0.90
4,nf_f4e65f8e18a8,21,Movie,2008,2000,2000s,18,"January 1, 2020",PG-13,123 min,...,United States,1,False,False,True,True,True,1.000,exact_title_year,0.90
5,nf_18f0ffc9ca6e,46,TV Show,2016,2010,2016-2019,10,"July 1, 2017",TV-MA,1 Season,...,Turkey,1,False,False,False,True,True,0.714,unmatched,0.00
6,nf_6f5d5d8a5929,122,Movie,2019,2010,2016-2019,7,"June 1, 2020",TV-MA,95 min,...,Egypt,1,False,False,True,True,True,1.000,exact_title_year,0.90
7,nf_db09b8438bb4,187,Movie,1997,1990,Pre-2000,29,"November 1, 2019",R,119 min,...,United States,1,False,False,False,True,True,0.714,unmatched,0.00
8,nf_8669252fff78,706,Movie,2019,2010,2016-2019,7,"April 1, 2019",TV-14,118 min,...,India,1,False,False,True,True,True,1.000,exact_title_year,0.90
9,nf_42bc58992dd0,1920,Movie,2008,2000,2000s,18,"December 15, 2017",TV-MA,143 min,...,India,1,False,False,True,True,True,1.000,exact_title_year,0.90

In [13]:
df_data_clean = df_data.iloc[:,1:]  
df_data_clean.head()

,title,type,release_year,release_decade,release_year_group,content_age,date_added,rating,duration,runtime_minutes,...,primary_country,country_count,is_original,is_recent_release,has_rating,has_cast,has_director,data_completeness_score,match_method,match_confidence
0,3%,TV Show,2020,2020,2020-2022,6,"August 14, 2020",TV-MA,4 Seasons,90.0,...,Brazil,1,False,False,True,True,False,0.857,fuzzy_title_year,0.89
1,7:19,Movie,2016,2010,2016-2019,10,"December 23, 2016",TV-MA,93 min,94.0,...,Mexico,1,False,False,True,True,True,1.000,exact_title_year,0.90
2,23:59,Movie,2011,2010,2010-2015,15,"December 20, 2018",R,78 min,78.0,...,Singapore,1,False,False,True,True,True,1.000,exact_title_year,0.90
3,9,Movie,2009,2000,2000s,17,"November 16, 2017",PG-13,80 min,79.0,...,United States,1,False,False,True,True,True,1.000,exact_title_year,0.90
4,21,Movie,2008,2000,2000s,18,"January 1, 2020",PG-13,123 min,123.0,...,United States,1,False,False,True,True,True,1.000,exact_title_year,0.90

In [17]:
mask = df_data_clean["countries"] == "France"
df_data_clean[mask]

,title,type,release_year,release_decade,release_year_group,content_age,date_added,rating,duration,runtime_minutes,...,primary_country,country_count,is_original,is_recent_release,has_rating,has_cast,has_director,data_completeness_score,match_method,match_confidence
49,10 jours en or,Movie,2012,2010,2010-2015,14,"July 1, 2017",TV-14,97 min,95.0,...,France,1,False,False,True,True,True,1.000,exact_title_year,0.9
77,2 Alone in Paris,Movie,2008,2000,2000s,18,"June 1, 2020",TV-MA,97 min,94.0,...,France,1,False,False,True,True,True,1.000,exact_title_year,0.9
203,A Mighty Team,Movie,2016,2010,2016-2019,10,"October 15, 2016",TV-MA,97 min,95.0,...,France,1,False,False,True,True,True,1.000,exact_title_year,0.9
248,A Very Secret Service,TV Show,2018,2010,2016-2019,8,"July 30, 2018",TV-MA,2 Seasons,NaN,...,France,1,False,False,False,True,False,0.571,unmatched,0.0
303,Ad Vitam,TV Show,2018,2010,2016-2019,8,"November 1, 2019",TV-MA,1 Season,60.0,...,France,1,False,False,True,True,False,0.857,exact_title_year,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7497,We Are One,Movie,2020,2020,2020-2022,6,"July 14, 2020",TV-MA,86 min,86.0,...,France,1,False,False,True,False,True,0.857,exact_title_year,0.9
7516,Wedding Unplanned,Movie,2017,2010,2016-2019,9,"October 19, 2017",TV-MA,94 min,94.0,...,France,1,False,False,True,True,True,1.000,exact_title_year,0.9
7535,West Coast,Movie,2016,2010,2016-2019,10,"October 28, 2016",TV-MA,81 min,80.0,...,France,1,False,False,True,True,True,1.000,exact_title_year,0.9
7604,Who Killed Little Gregory?,TV Show,2019,2010,2016-2019,7,"November 20, 2019",TV-MA,1 Season,60.0,...,France,1,False,False,True,False,False,0.714,exact_title_year,0.9
7765,Zig & Sharko,TV Show,2016,2010,2016-2019,10,"December 1, 2017",TV-Y7,1 Season,NaN,...,France,1,False,False,False,False,False,0.429,unmatched,0.0