<img src="https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg" />

# Visualizing earthquakes🌍

You work as a **AI analyst at a global insurance company**. The risk team prices natural disaster coverage. They need clear visuals to understand where and when earthquakes happen, how strong they are, and how the pattern changes over time. Static charts are not enough. The team needs interactive tools they can explore during meetings with underwriters.

## Dataset 

The file `earthquakes.csv` accompanies this notebook. Download it from the course resources.

It contains about 23,000 events recorded between 1965 and 2024. Each row is one event with its date, location, type, depth in kilometers, and magnitude. Place the CSV file in the same folder as this notebook before running the cells.

## Setup

Run the cell below to install the libraries. Plotly handles the charts. Pandas handles the data.

### Instructions

In the next code cell, run a single `%pip install` magic command to install the two libraries needed for this notebook:

1. Use the Jupyter `%pip` magic (not bare `pip`) so the install happens in the kernel that is actually running this notebook.
2. Pass two package names: `plotly` and `pandas`.
3. Add the `--quiet` flag at the end so the install logs do not flood the cell output.

<Note type='tip'>
**Why `%pip` and not `!pip`?** `%pip` is aware of the current kernel and installs into the same Python environment Jupyter is using. `!pip` runs in a subshell that may target a different Python, leading to confusing "module not found" errors right after a successful install.
</Note>

In [1]:
%pip install plotly pandas --quiet

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: C:\Users\CMeny\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

### Instructions

In the next code cell, import the libraries you will use throughout the notebook:

1. Import `pandas` and give it the conventional alias `pd`.
2. Import `plotly.express` and give it the conventional alias `px`. Plotly Express is the high-level API: one function call gives you a complete chart.
3. Import `plotly.graph_objects` and give it the conventional alias `go`. Graph Objects is the low-level API. Use it when you need fine control (range sliders, custom buttons, mixed chart types).
4. From `plotly.subplots`, import the `make_subplots` function. You will use it to build a multi-row figure in Task 5.

In [1]:
# your code here
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

## Task 1: Load the dataset

### Instructions

The CSV file lives in a folder named `src/` next to this notebook. In the next code cell:

1. Load `src/earthquakes.csv` into a DataFrame called `df` using `pd.read_csv(...)`.
2. Convert the `Date` column from text to a real datetime using `pd.to_datetime(df["Date"])`. Reassign the result back to `df["Date"]`.
3. Print the shape of the DataFrame using an f-string: `print(f"Dataset shape: {df.shape}")`. The shape is a tuple `(rows, columns)`.
4. As the **last** expression in the cell, write `df.head()` (without `print(...)`). Jupyter will render the first five rows as a formatted table.

<Note type='tip'>
**Why convert dates?** Strings sort alphabetically (`"2010-01-02"` comes before `"2010-1-3"`) and Plotly cannot space them properly on a time axis. A real datetime type fixes both issues at once.
</Note>

In [6]:
# your code here
df = pd.read_csv("src/earthquakes.csv")
df["Date"] = pd.to_datetime(df["Date"])
print(f"Dataset shape: {df.shape}")
print(df.head())

Dataset shape: (23000, 6)
        Date  Latitude  Longitude        Type  Depth  Magnitude
0 1965-01-02   45.1595  -123.6312  Earthquake  145.8        6.7
1 1965-01-03  -16.3286   175.9818  Earthquake   58.9        5.7
2 1965-01-04   31.0608    68.4153  Earthquake   68.9        5.6
3 1965-01-06  -20.7233   129.3217  Earthquake  121.0        5.8
4 1965-01-10  -22.6911   166.1065  Earthquake  115.4        6.7

## Task 2: Inspect the dataset

Look at basic statistics and data types. This step confirms the data is ready to plot.

### Instructions

You will use **two short code cells** for this task, one per check.

**First code cell**, summary statistics:

1. Call `df.describe()` as the only line of the cell. Jupyter renders the result as a table showing count, mean, standard deviation, min, max, and quartiles for every numeric column.

**Second code cell**, column types:

1. Call `df.dtypes` as the only line of the cell. The output lists every column with its Python type. Confirm that `Date` is `datetime64[ns]` (set in Task 1) and that `Latitude`, `Longitude`, `Depth`, and `Magnitude` are numeric (`float64` or `int64`).

<Note type='tip'>
**Why two separate cells?** Jupyter only renders the value of the **last** expression in a cell. Splitting them keeps both outputs visible. If you put `df.describe()` and `df.dtypes` in one cell, only the second one displays.
</Note>

In [14]:
# Show summary statistics for the numeric columns
print(df.describe())
# your code here
df.dtypes

                             Date      Latitude     Longitude         Depth  \
count                       23000  23000.000000  23000.000000  23000.000000
mean   1995-01-23 19:09:59.791304     15.513962      3.969896     70.514704
min           1965-01-02 00:00:00    -53.424700   -179.996100      0.000000
25%           1979-12-23 18:00:00    -10.094000    -93.259775     20.200000
50%           1995-03-25 00:00:00     20.611100     -7.438300     48.000000
75%           2010-02-16 00:00:00     38.169275    115.054500     97.625000
max           2024-12-30 00:00:00     84.341800    179.992000    639.900000
std                           NaN     29.025011    110.024623     71.364236

          Magnitude
count  23000.000000
mean       6.104548
min        5.500000
25%        5.700000
50%        5.900000
75%        6.300000
max        9.500000
std        0.594134
Date         datetime64[us]
Latitude            float64
Longitude           float64
Type                    str
Depth               float64
Magnitude           float64
dtype: object

In [ ]:
# Check the data types of each column

# your code here

Date         datetime64[ns]
Latitude            float64
Longitude           float64
Type                 object
Depth               float64
Magnitude           float64
dtype: object

## Task 3: Plot the number of events over time

The risk team's first question is simple: how many events do we record each year? A histogram with one bar per year answers this directly.

Plotly Express handles the binning automatically when the x-axis is a date column. You write one line and get a working chart.

### Instructions

In the next code cell, build a histogram with Plotly Express:

1. Call `px.histogram(...)` and assign the result to a variable called `fig`. Pass these arguments:
   - The DataFrame: `df`.
   - `x="Date"`. Plotly automatically buckets datetime values into yearly bins by default.
   - `title="Number of recorded events per year"`.
   - `labels={"Date": "Year", "count": "Number of events"}`. The `labels` dict renames the axis titles so the chart reads cleanly without needing extra `update_xaxes` calls.
2. Call `fig.show()` to display the chart.

<Note type='tip'>
**Plotly Express vs. Graph Objects.** `px.histogram` is one line and good enough for most cases. When you need extras like a range slider or custom buttons (Tasks 4 and 6), you switch to `go.Figure` and add the building blocks yourself.
</Note>

In [23]:
# your code here
fig = px.histogram(df, x="Date", 
                   title="Number of recorded events per year",
                   labels={"Date": "Year", "count": "Number of events"})
fig.show()

## Task 4: Add a range slider for daily counts

The yearly histogram hides daily variation. The risk team wants to zoom into specific weeks during major events like the 2011 Tohoku earthquake or the 2010 Haiti earthquake. A **range slider** lets them drag a window across the time axis.

Plotly Express does not support range sliders directly. You switch to **Plotly Graph Objects**, which gives you fine control over every chart element.

### Instructions

In the next code cell, build the same kind of histogram but with daily bins and an interactive range slider:

1. Create an empty figure: `fig = go.Figure()`.
2. Add a histogram trace with `fig.add_trace(...)`. Inside, build the trace with `go.Histogram(...)` and pass:
   - `x=df["Date"]`.
   - `xbins=dict(size="D1")`. The `"D1"` string means "one day per bin". Plotly accepts shortcuts like `"M1"` (month), `"W1"` (week), and `"D1"` (day).
   - `name="Daily events"`.
3. Configure the layout with `fig.update_layout(...)`. Pass:
   - `title="Daily number of events (drag the slider to zoom)"`.
   - `xaxis=dict(title="Date", rangeslider=dict(visible=True), type="date")`. The `rangeslider=dict(visible=True)` line is the one that adds the slider strip below the chart. The `type="date"` setting tells Plotly to treat the axis as time.
   - `yaxis=dict(title="Number of events per day")`.
4. Call `fig.show()`.

<Note type='tip'>
**`go.Figure` workflow.** With Graph Objects you always do the same three steps: create an empty `go.Figure`, add one or more traces with `add_trace`, then configure the look with `update_layout`. Once you internalize that pattern, every Plotly chart is just a variation.
</Note>

In [29]:
# your code here
fig = go.Figure()
fig.add_trace(go.Histogram(x=df["Date"],
                           xbins=dict(size="D1"),
                           name="Daily events"))
fig.update_layout(title="Daily number of events (drag the slider to zoom)",
                  xaxis=dict(title="Date", rangeslider=dict(visible=True), type="date"),
                  yaxis=dict(title="Number of events per day"))
fig.show()

## Task 5: Check for seasonality with subplots

Some natural phenomena follow seasons. Hurricanes peak in late summer. Wildfires peak in dry months. The risk team wants to check if earthquakes show a seasonal pattern.

You build five small histograms side by side, one per recent year. Each histogram shows monthly counts. If a season pattern exists, you see it repeat across the five charts.

To get the month and year, add two new columns to the DataFrame.

### Instructions

This task uses **three code cells**.

**First code cell**, add helper columns:

1. Create a new column `df["Year"]` from `df["Date"].dt.year`. The `.dt` accessor exposes datetime parts on a datetime column.
2. Create a new column `df["Month"]` from `df["Date"].dt.month`. Values run from 1 (January) to 12 (December).
3. As the last expression, write `df.head()` to confirm the two new columns appear.

**Second code cell**, pick the five most recent years:

1. Find the largest year in the dataset: `max_year = df["Year"].max()`.
2. Build a list called `recent_years` containing the five years from `max_year` down to `max_year - 4`. Start with an empty list, loop with `for offset in range(5)` and append `max_year - offset` each time.
3. Sort the list with `recent_years.sort()` so it runs from oldest to newest.
4. Print it: `print("Years to plot:", recent_years)`.

**Third code cell**, build the 5-row subplot grid:

1. Create the figure with `make_subplots(...)`. Pass:
   - `rows=5`, `cols=1`.
   - `subplot_titles=["Year " + str(y) for y in recent_years]` to give each row a title.
   - `vertical_spacing=0.05` to leave a small gap between rows.
2. Add one histogram per year. Start a counter `row_position = 1`, then loop with `for year in recent_years:`. Inside the loop:
   - Filter to that year: `year_data = df[df["Year"] == year]`.
   - Build a `go.Histogram(...)` trace with `x=year_data["Month"]`, `xbins=dict(start=0.5, end=12.5, size=1)` (one bin per month), `name=str(year)`, and `showlegend=False`.
   - Add it with `fig.add_trace(trace, row=row_position, col=1)`.
   - Increment the counter: `row_position = row_position + 1`. Subplot rows in Plotly start at 1, not 0.
3. Force the x-axes to show every month from 1 to 12: `fig.update_xaxes(tickmode="linear", tick0=1, dtick=1)`.
4. Configure the layout: `fig.update_layout(height=900, title="Monthly event counts for the five most recent years")`. The taller height keeps each subplot readable.
5. Call `fig.show()`.

<Note type='tip'>
**Why `start=0.5, end=12.5, size=1`?** Each month gets its own bin centered on its integer. Bin 1 covers `[0.5, 1.5)`, bin 2 covers `[1.5, 2.5)`, and so on. Without these bounds, Plotly might merge two months into one bar.
</Note>

In [ ]:
# Add month and year columns

# your code here

        Date  Latitude  Longitude        Type  Depth  Magnitude  Year  Month
0 1965-01-02   45.1595  -123.6312  Earthquake  145.8        6.7  1965      1
1 1965-01-03  -16.3286   175.9818  Earthquake   58.9        5.7  1965      1
2 1965-01-04   31.0608    68.4153  Earthquake   68.9        5.6  1965      1
3 1965-01-06  -20.7233   129.3217  Earthquake  121.0        5.8  1965      1
4 1965-01-10  -22.6911   166.1065  Earthquake  115.4        6.7  1965      1

In [9]:
# Pick the five most recent years
# your code here

Years to plot: [np.int32(2020), np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024)]

In [10]:
# Build a subplot grid with one column and five rows
# your code here

## Task 6: Show the proportion of each event type

The dataset contains four event types. Before focusing on earthquakes, confirm how rare the other types are. A pie chart answers this in one glance.

### Instructions

In the next code cell:

1. Count how many rows fall into each category of the `Type` column with `df["Type"].value_counts()`. Store the result in `type_counts`. The result is a pandas Series with the type as the index and the count as the value.

2. Convert the Series into a regular DataFrame with two columns. Pandas `value_counts()` returns a Series where the index is the category, and Plotly Express prefers a DataFrame:
   - `type_counts_df = type_counts.reset_index()`. This turns the index into a real column.
   - Rename the columns explicitly: `type_counts_df.columns = ["Type", "Count"]`.

3. Build the pie chart with `px.pie(...)`. Assign to `fig`. Pass:
   - The DataFrame: `type_counts_df`.
   - `names="Type"` (the slice labels).
   - `values="Count"` (the slice sizes).
   - `title="Proportion of each event type"`.

4. Call `fig.show()`.

In [11]:
# Count the events of each type
# your code here

## Task 7: Filter to earthquakes and study magnitudes and depths

Filter the DataFrame to keep only earthquake rows. Then plot two distributions: magnitude and depth. The risk team uses these distributions to set premium thresholds. An earthquake at magnitude 7.5 costs the company very differently from one at magnitude 5.5.

### Instructions

This task uses **three code cells**.

**First code cell**, build the filtered DataFrame:

1. Keep only the rows where `Type` equals `"Earthquake"`: `earthquakes = df[df["Type"] == "Earthquake"]`.
2. Reset the index so the new DataFrame has clean numbering starting at 0: `earthquakes = earthquakes.reset_index(drop=True)`. The `drop=True` argument throws away the old index instead of turning it into a column.
3. Print how many earthquakes you kept: `print(f"Number of earthquakes: {len(earthquakes)}")`.
4. As the last expression, call `earthquakes.describe()` to see summary statistics for the filtered data.

**Second code cell**, magnitude distribution:

1. Call `px.histogram(...)` and store the result in `fig_magnitude`. Pass `earthquakes`, `x="Magnitude"`, `nbins=40`, and `title="Distribution of earthquake magnitudes"`.
2. Call `fig_magnitude.show()`.

**Third code cell**, depth distribution:

1. Call `px.histogram(...)` and store the result in `fig_depth`. Pass `earthquakes`, `x="Depth"`, `nbins=40`, and `title="Distribution of earthquake depths (kilometers)"`.
2. Call `fig_depth.show()`.

<Note type='tip'>
**Why `nbins=40`?** The default bin count is small and hides skew. With 40 bins you can clearly see the long right tail of the magnitude distribution, which is the whole point of the chart for the risk team.
</Note>

In [12]:
# your code here

Number of earthquakes: 22320

,Date,Latitude,Longitude,Depth,Magnitude,Year,Month
count,22320,22320.000000,22320.000000,22320.000000,22320.000000,22320.000000,22320.000000
mean,1995-01-28 08:39:36.774193536,15.520806,3.924985,70.450063,6.104368,1994.577285,6.506720
min,1965-01-02 00:00:00,-53.424700,-179.996100,0.000000,5.500000,1965.000000,1.000000
25%,1979-12-29 00:00:00,-10.108300,-93.357300,20.200000,5.700000,1979.000000,3.000000
50%,1995-04-02 00:00:00,20.613300,-8.196100,48.000000,5.900000,1995.000000,7.000000
75%,2010-02-16 00:00:00,38.192725,115.091150,97.700000,6.300000,2010.000000,10.000000
max,2024-12-30 00:00:00,84.341800,179.971300,639.900000,9.500000,2024.000000,12.000000
std,NaN,29.042048,110.058350,71.086453,0.593429,17.295611,3.451825

In [ ]:
# Distribution of magnitudes
# your code here

In [ ]:
# Distribution of depths
# your code here

## Task 8: Track the daily mean magnitude over time

The risk team wants to know if the average earthquake is getting stronger over time. A line chart of daily mean magnitude answers this. Add a horizontal reference line at the overall mean. Days above the line are stronger than average. Days below are weaker.

You do this in three steps: aggregate the data, build the chart, add the reference line.

### Instructions

This task uses **three code cells**.

**First code cell**, aggregate to daily mean magnitude:

1. Group the earthquakes by calendar day and take the mean of the `Magnitude` column. Pandas can group on the date part of a datetime column directly:
   ```python
   daily_mean = earthquakes.groupby(earthquakes["Date"].dt.date)["Magnitude"].mean()
   ```
2. The result is a Series. Convert it to a DataFrame with `daily_mean = daily_mean.reset_index()`.
3. Rename the columns to friendly names: `daily_mean.columns = ["Day", "MeanMagnitude"]`.
4. Convert the `Day` column back to a real datetime so Plotly draws the time axis correctly: `daily_mean["Day"] = pd.to_datetime(daily_mean["Day"])`.
5. As the last expression, call `daily_mean.head()` to inspect the result.

**Second code cell**, compute the overall mean:

1. `overall_mean = earthquakes["Magnitude"].mean()`.
2. `print(f"Overall mean magnitude: {overall_mean:.2f}")`. The `:.2f` format keeps two decimal places.

**Third code cell**, build the chart:

1. Create an empty figure: `fig = go.Figure()`.

2. Add the daily mean as a line trace. Inside `fig.add_trace(...)`, build a `go.Scatter(...)` with:
   - `x=daily_mean["Day"]`.
   - `y=daily_mean["MeanMagnitude"]`.
   - `mode="lines"` (a Scatter is a line chart only when you set this).
   - `name="Daily mean"`.
   - `line=dict(width=1)` to make the line thin enough that the spikes show up.

3. Add a horizontal reference line with `fig.add_hline(...)`. Pass:
   - `y=overall_mean`.
   - `line_dash="dash"` for a dashed style.
   - `line_color="red"`.
   - `annotation_text=f"Overall mean = {overall_mean:.2f}"` (a label drawn next to the line).
   - `annotation_position="top left"`.

4. Configure the layout with `fig.update_layout(...)`:
   - `title="Daily mean earthquake magnitude over time"`.
   - `xaxis=dict(title="Date", rangeslider=dict(visible=True), type="date")` to add the same range slider you used in Task 4.
   - `yaxis=dict(title="Mean magnitude")`.

5. Call `fig.show()`.

<Note type='tip'>
**`go.Scatter` is the all-purpose trace.** Despite the name, it draws lines, points, or both depending on `mode`. Use `mode="lines"` for a line chart, `mode="markers"` for a scatter plot, and `mode="lines+markers"` to show both.
</Note>

In [15]:
# Aggregate to daily mean magnitude
# your code here

         Day  MeanMagnitude
0 1965-01-02            6.7
1 1965-01-03            5.7
2 1965-01-04            5.6
3 1965-01-06            5.8
4 1965-01-10            6.5

In [16]:
# Step 2: compute the overall mean magnitude
# your code here

Overall mean magnitude: 6.10

In [ ]:
# Step 3: build the chart with a range slider and a reference line
# your code here

# Daily mean magnitude as a line
# your code here

# Horizontal reference line at the overall mean
# your code here

## Task 9: Plot earthquakes on a world map

The final question is geographic. Where do earthquakes cluster? A scatter plot on a world map answers this. Color each point by magnitude so the eye picks out the strongest events first.

Plotly Express has a function called `scatter_geo` that draws points on a world map. It does not require any external map service or API key.

### Instructions

In the next code cell:

1. Sample 5,000 earthquakes from the full filtered set. Plotting all 23,000 would clutter the map and slow the browser:
   - `sample_size = 5000`.
   - `earthquakes_sample = earthquakes.sample(n=sample_size, random_state=42)`. The `random_state=42` makes the sample reproducible: every run gets the same 5,000 rows.

2. Build the map with `px.scatter_geo(...)` and assign it to `fig`. Pass:
   - The DataFrame: `earthquakes_sample`.
   - `lat="Latitude"` and `lon="Longitude"`. These are the column names that hold the coordinates.
   - `color="Magnitude"` so each point is colored by its strength.
   - `color_continuous_scale="Reds"` for a white-to-red gradient (stronger earthquakes appear darker red).
   - `size="Magnitude"` to also vary point size with magnitude.
   - `size_max=8` so the largest points stay readable.
   - `title="Earthquake locations colored by magnitude"`.
   - `projection="natural earth"`. This is the most balanced world projection: no extreme distortion at the poles.

3. Call `fig.show()`.

<Note type='tip'>
**`random_state=42` is not magic.** Any integer works. The point is to **fix** it so the result is reproducible. If you omit it, every run produces a different sample and you cannot compare results across runs.
</Note>

In [ ]:
# Sample 5000 earthquakes for clearer plotting (full dataset would clutter the map)
# your code here

## Task 10: Animate the map year by year (Optional)

The risk team's last question: does the geographic pattern change over time? An animated map plays one frame per year. The play button at the bottom lets the user start, pause, and scrub through the years.

You add one argument to `scatter_geo`: `animation_frame="Year"`. Plotly handles the rest.

### Instructions

In the next code cell:

1. Make a copy of the sample so you do not modify the original: `earthquakes_sample_with_year = earthquakes_sample.copy()`.
2. Add a `Year` column from the `Date` column: `earthquakes_sample_with_year["Year"] = earthquakes_sample_with_year["Date"].dt.year`.
3. Sort the DataFrame by year so the animation plays in chronological order: `earthquakes_sample_with_year = earthquakes_sample_with_year.sort_values("Year")`.
4. Call `px.scatter_geo(...)` and assign the result to `fig`. Pass the same arguments as Task 9 plus one extra:
   - DataFrame: `earthquakes_sample_with_year`.
   - `lat="Latitude"`, `lon="Longitude"`.
   - `color="Magnitude"`, `color_continuous_scale="Reds"`.
   - `size="Magnitude"`, `size_max=8`.
   - `animation_frame="Year"`. This is the new argument: Plotly creates one frame per unique value of this column and adds a play button and a slider at the bottom of the chart.
   - `title="Earthquakes year by year"`.
   - `projection="natural earth"`.
5. Call `fig.show()`.

<Note type='tip'>
**Sort before animating.** Plotly plays the frames in the order it encounters new values in `animation_frame`. If you do not sort, the animation may jump around (1995, 2010, 1972, ...) instead of playing in time order.
</Note>

In [ ]:
# Add the Year column to the sample
# your code here

# Sort by year so the animation plays in order
# your code here